os: linux
language: generic
services:
  - docker
script:
  - curl -LO https://raw.githubusercontent.com/clearfraction/tools/master/scratch-build.sh && chmod +x scratch-build.sh
  - docker run --privileged --cap-add=SYS_ADMIN -e GITLAB_API_KEY=$GITLAB_API_KEY -v $(pwd):/home clearlinux:latest sh -c "cd /home && ./scratch-build.sh"
